### PR TITLE
Add Connection, NamedConnection and Relation classes

### PR DESCRIPTION
**Pull request by kgpayne**
New Connection, NamedConnection and Relation classes, added to support extraction of metadata via [tap-tableau-server](https://github.com/tailsdotcom/tap-tableau-server). From the readme:

> tap-tableau-server is a Singer tap for Tableau Server, focused (currently) on extracting details embedded inside Workbook files. This includes Datasources, Connections and Relations, as well as retrieving table references from embedded Custom SQL text fields inside Relation entities.
>
> Extracting the specifics of Datasources, Connections, Relations and Table References from each Workbook help answer questions like:
>
> - Which Workbooks depend on which tables in which databases?
> - How many Workbooks depend on Excel, CSV or Google Sheets?
> - Who's credentials are used for embedded connections, in which Workbooks?
>
> Having answers to all of these questions has helped us with wrangling our Tableau Server instance, which is several years old and has over 1000 Workbooks.
>
> In future, we hope to extend this tap to cover other metadata that is exposed by the Tableau Server API's directly (esp. Published Connections and child objects). PR submission very welcome. Watch this space!

### CODE REVIEW

**Comment by jacalata** [comment]
Interesting! Could you please submit a Contributor License Agreement described here: https://tableau.github.io/contributing.html?

**Comment by jacalata** [comment]
Unfortunately we absolutely can't merge code from someone who hasn't agreed to our CLA. Hopefully @kgpayne is still available and might come back to sign it and submit!

**Comment by jacalata** [comment]
But I can switch the PR to branch from development instead of master, and I'll try and add some tests for it so it's easier to finish if they do come back.

**Comment by bryceglarsen** [comment]
Completely understandable @jacalata - wasn’t sure if CLA had been signed. Thank you though!

**Comment by kgpayne** [comment]
Hey 👋 Thanks for checking this out! I recently moved roles, and am no longer at `tailsdotcom/` to be able to sign an Organisational CLA on their behalf. However @alanmcruickshank might be able to 🙂 He is familiar with this work. I also don't have access to a Tableau instance anymore, so really appreciate your work on tests @jacalata 🙏

**Comment by jacalata** [comment]
Hi @alanmcruickshank - are you interested/able to sign a CLA so I could merge this work into the tool? I don't think the bot is smart enough to understand that, so we might just need it over email.

**Comment by jacalata** [comment]
I finally actually pinged Dev so hopefully will get this wrapped up soon

**Comment by waltonereed** [comment]
Any updates here? Am interested in the relation class too.

**Comment by kgpayne** [comment]
Closing as approaching 3 years old and very stale 🤷‍♂️

**Pull request closed without merging**
