### PR TITLE
add shape property

### PR DESCRIPTION
**Pull request by dev-mkc19**
Adding ability to get shapes name from workbook

### CODE REVIEW

**Comment by dev-mkc19** [comment]
@RussTheAerialist hello! I would like to being part of contributors by added some improvements. But my merge request is still opened. What should I do to speed up this process?

**Comment by jacalata** [comment]
Hi @dev-mkc19 - sorry for the long silence. If you're still interested, could you add a test or a sample that shows your change working?

**Comment by bcantoni** [comment]
Confirmed we've received the CLA from @dev-mkc19, so we are all set on that part of this PR.

**Comment by dev-mkc19** [comment]
@jacalata I added some tests and rebase my commits to be up to date, but think it wasn't good idea because some waste commits is included. What do you think?

**Comment by jacalata** [comment]
I'm going to try rebasing this onto the dev branch, and that should get rid of all the unnecessary commits. If you would like to do that yourself then of course go ahead 😀

**Comment by dev-mkc19** [comment]
No problem, I’ll do this. But I want to be sure that my work won’t be wasted, because 1,5 year for PR it’s crazy loooong.

**Comment by jacalata** [comment]
It is. I will release it myself.

**Comment by dev-mkc19** [comment]
Just remember that I'm still waiting 😃

**Comment by jacalata** [comment]
I remember!

**Comment by jacalata** [comment]
And there you go, 0.8 :) It'll go up on pypi during the week.

**Comment by dev-mkc19** [comment]
Yeah, already saw the release. It's cool. Hope to be able to bring some more benefits.

**Pull request merged**
