### PR TITLE
Update field.py

### PR DESCRIPTION
**Pull request by rimishra-equinix**

### CODE REVIEW

**Comment by rimishra-equinix** [comment]
Added code to get info if the fields is hidden or not

**Comment by rimishra-equinix** [comment]
> It also recommended to provide tests and update documentation.

Thank you Mikhail for your feedback. However, I am very new to Python and GIT have been self-learning Python. I have written the Python code to extract similar information including additional data like if the field is hidden or not, and wanted to add that capability in the document-api. I am not sure how can I test the dev branch and it will be helpful if we can get on a call and you can walk me through that?

**Comment by dev-mkc19** [comment]
@rimishra-equinix You can write simple unit tests (see example in test folder) that will confirmed everything works as expected. It will help in future to add new functionality and be sure that nothing was broken. I'm sure you can, it's easy.

Changing documentation it's easy too. Edit api-ref.md file in doc folder as a text.

**Comment by jacalata** [comment]
merging into a staging branch to combine with the other changes I retrieved

**Pull request merged**
