### PR TITLE
Get query string

### PR DESCRIPTION
**Pull request by martydertz**
adding _get_custom_sql method to Datasource class. Returns SQL query as a string

### CODE REVIEW

**Comment by jacalata** [comment]
Is it possible for you to rebase this onto the development branch?

**Comment by martydertz** [comment]
Will do

**Comment by bcantoni** [comment]
@martydertz thanks so much for your contribution here. Could you please submit a Contributor License Agreement described here: https://tableau.github.io/contributing.html

**Comment by martydertz** [comment]
@bcantoni I just e-signed & e-mailed the signed CSA to github@tableau.com

**Comment by bcantoni** [comment]
@martydertz thank you - the CLA has been received and you are good to go. @jacalata when you get a chance please review.

**Review by jacalata — APPROVED** [review]

**Pull request merged**
