### PR TITLE
Implemented #109 #110

### PR DESCRIPTION
**Pull request by r-richmond**
Thought I'd take a stab at implementing my requests #109 #110. I noticed I was going to have merge conflicts with development so I merged ahead of time and wanted to make sure I followed the standards in that branch so I merged ahead of time.

Also tested on some of my workbooks (10.1) without issues.

### CODE REVIEW

**Comment by r-richmond** [comment]
Please email me the CLA at your earliest convenience

**Comment by t8y8** [comment]
Thank you for your PR AND for including docs updates, @r-richmond! 

Please update PR to merge against tableau:development -- it's currently pointing to master.

Once we have the CLA all processed I will do a proper review!

(And happy holidays!)

**Comment by r-richmond** [comment]
Emailed github@tableau.com with a signed copy of the CLA & Changed the destination branch.

Cheers & Happy Holidays too!

**Comment by benlower** [comment]
@t8y8 CLA received from Ryan

**Comment by r-richmond** [comment]
Ok definitely pushed me beyond my comfort zone with git but I think I've done everything you requested, yay for growth. 

Also added some tests, extended a couple to cover the new features, and tweaked the connection xml to include the query band. @t8y8 Let me know if this works for you.

**Comment by t8y8** [comment]
:rocket: this same project has forced some git-fu upon me as well!
The changes look good, and the tests look good.

I'd like @RussTheAerialist to weigh in as well -- just because I know we're planning some work that would change how we update the document and the in-memory objects. Every new attribute we add is giving ourselves a teeny bit more work for that project... but given that this is simple, tested, and addresses a very common use case, I would be in favor of merging this.

**Comment by RussTheAerialist** [comment]
@t8y8 I'm fine with 🚀 on this change.  @r-richmond Thank you so much for doing this!

I know it will help more than a few people in the short term, and I'm not quite ready for the changes I'm planning to the internals.  It does add some "cost" for me, but it also gives me a set of changes that help me validate the work that I'm hoping to finish this month :)

**Comment by r-richmond** [comment]
Awesome, happy to contribute. Just out of curiosity how often does the dev branch get merged into master? aka when should I expect to see my changes in the version i download from pip?

**Comment by RussTheAerialist** [comment]
Usually we do it once a month, but since We didn't have one for December, I've been talking about cutting a release on Friday and I think everyone is supportive of that plan especially because of this change :)

**Comment by benlower** [comment]
@r-richmond @RussTheAerialist did this item fully address #109 and #110? If so, can those be closed? if not, what still needs to be done?

**Comment by t8y8** [comment]
Yup, this an be closed!

**Pull request merged**
