### PR TITLE
add dbclass name for Cisco Information Server

### PR DESCRIPTION
**Pull request by carlsonp**

### CODE REVIEW

**Comment by t8y8** [comment]
@RussTheAerialist does this require a CLA?

@carlsonp looks fine to me, just need to check on the above first.

**Comment by RussTheAerialist** [comment]
@t8y8 I don't know, and @benlower left for the day so I won't be able to ask until Monday.

**Comment by carlsonp** [comment]
Since it's a simple fix and I'm not quite sure what is necessary for CLA, it might be better if one of you fine folks just committed the fix?

**Comment by RussTheAerialist** [comment]
Oh yeah, let's just merge that in, that's really simple.

**Pull request merged**
